language: node_js
node_js:
  - "7"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install --save firebase-admin@4.2.1 
  - cd functions && npm install firebase-functions@latest --save && cd -
  - cd functions && npm install && cd -

after_success:
  - firebase deploy --token $FIREBASE_TOKEN 
