language: node_js
node_js:
  - "6"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install firebase-functions@latest --save
after_success:
  - firebase deploy --token $FIREBASE_TOKEN 
